version: "3.3"

services:
  db:
    image: postgres:15-alpine
    container_name: "postgres_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pg_db
      - POSTGRES_PORT=5432
      - PGDATA=/var/lib/postgresql/repository/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/repository/pgdata
    ports:
      - "5432:5432"
    restart: always
#    env_file: # для хранения secrets правильнее использовать .env-файл
#      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - data_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"

  nats:
    image: nats-streaming:latest
    container_name: "nats_server"
    ports:
      - "4222:4222"
    command: ["--cluster_id=my_cluster"]



volumes:
  postgres_data:
  data_pgadmin:
